### ISSUE TITLE
Figma Mockup/ Site map

### ISSUE THREAD

**Issue by MeiH10** [MeiH10/RPI-EventHub#1]
Create Figma Mockup/ Site map for the web app

**Comment by FlyM1ss** [comment]
![basic_design_components](https://github.com/MeiH10/RPI-EventHub/assets/112596144/acd95e93-5cfd-44dc-8b23-4cc144576f75)
![basic_design_components_2](https://github.com/MeiH10/RPI-EventHub/assets/112596144/06d595e3-d1b9-4a7b-9867-1d1237cf5904)
![event_homepage_sketching](https://github.com/MeiH10/RPI-EventHub/assets/112596144/1cf1c8bf-2bd9-4be6-a4e7-535d88b4f2ce)
![single_event_page](https://github.com/MeiH10/RPI-EventHub/assets/112596144/5eb6a620-8a43-466b-9f7b-3897dba3275e)
![single_event_page_sketch_1](https://github.com/MeiH10/RPI-EventHub/assets/112596144/3a29e609-bbc1-4b60-be8b-586d4f98d078)
![single_event_page_sketch_2](https://github.com/MeiH10/RPI-EventHub/assets/112596144/5653c41a-2004-4e27-86c1-234bb71179c4)

Current mockups ↑

**Comment by FlyM1ss** [comment]
![single_event_page_protrait](https://github.com/MeiH10/RPI-EventHub/assets/112596144/10758621-0775-4f69-9462-2ee379fb4647)

Single Event Page - Portrait ↑
