### ISSUE TITLE
"How to use" guide

### ISSUE THREAD

**Issue by MeiH10** [MeiH10/RPI-EventHub#91]
Create a "How to use" guide for users. Showcase the main features. Would be nice if screenshots is included.

**Comment by harikim17** [comment]
[Navigating RPIEventHub.pdf](https://github.com/MeiH10/RPI-EventHub/files/15103454/Navigating.RPIEventHub.pdf)

**Comment by harikim17** [comment]
[Navigating RPIEventHub.pdf](https://github.com/MeiH10/RPI-EventHub/files/15103494/Navigating.RPIEventHub.pdf)
